@startuml test
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container_Boundary(webApp, "Bplus Tree Visualizer") {
    Component(UI, "UI", "HTML/TypeScript", "Get user input")
    Component(algoVis, "Algorithm Visualizer", "TypeScript Class", "The logic that implements the Bplus Tree Algorithm and generates svg animation based on that algorithm.")
    Component(animationManager, "Animation Manager", "TypeScript Class/anime.js", "Keeps track of svg animation state and provides building blocks for animating a bplus tree.")
    Component(algoStepsHistory, "Algorithm Steps History", "TypeScript Class", "Defines and interface that can be used to keep track of algorithm steps and move forward and backward through them.")
}

Rel(UI, algoVis, "Uses");
Rel(UI, algoStepsHistory, "Uses");
Rel(algoVis, animationManager, "Uses");
Rel(algoVis, algoStepsHistory, "Uses");

@enduml
